"""Research layer contracts and state exports."""

from qwen3_coder_next.research.schemas import (
    EvidenceFreshness,
    EvidenceItem,
    EvidenceProvenance,
    RESEARCH_SCHEMA_VERSION,
    ResearchBudget,
    ResearchNextAction,
    ResearchPacket,
    ResearchRequest,
    ResearchStateStatus,
    ResearchTaskType,
    SourceHandle,
    SourcePolicy,
    SourceType,
)
from qwen3_coder_next.research.normalization import (
    MalformedResearchRequestError,
    MalformedSourcePolicyError,
    ResearchNormalizationError,
    ResearchNormalizationResult,
    ResearchRequestNormalizer,
    normalize_research_request,
)
from qwen3_coder_next.research.scanner import (
    LocalRepositoryScanner,
    MalformedRepositoryScanRequestError,
    RepositoryScanError,
    RepositoryScanResult,
    scan_local_repository,
)
from qwen3_coder_next.research.fetchers import (
    DocumentFetcher,
    ErrorFetcher,
    LogFetcher,
    MalformedResearchFetchRequestError,
    ResearchFetchError,
    ResearchFetchResult,
)
from qwen3_coder_next.research.evidence import (
    MalformedResearchEvidenceError,
    ResearchEvidenceNormalizationError,
    ResearchEvidenceNormalizationResult,
    ResearchEvidenceNormalizer,
    normalize_research_evidence,
)
from qwen3_coder_next.research.packet_assembly import (
    MalformedResearchPacketInputError,
    ResearchPacketAssemblyError,
    ResearchPacketAssembler,
    assemble_research_packet,
)
from qwen3_coder_next.research.pipeline import (
    MalformedResearchPipelineInputError,
    ResearchPipeline,
    ResearchPipelineError,
    ResearchPipelineResult,
    run_research_pipeline,
)
from qwen3_coder_next.research.state import ResearchRevision, ResearchState

__all__ = [
    "EvidenceFreshness",
    "EvidenceItem",
    "EvidenceProvenance",
    "RESEARCH_SCHEMA_VERSION",
    "ResearchBudget",
    "ResearchNextAction",
    "ResearchPacket",
    "ResearchRequest",
    "ResearchRevision",
    "ResearchState",
    "ResearchStateStatus",
    "ResearchNormalizationError",
    "ResearchNormalizationResult",
    "ResearchRequestNormalizer",
    "ResearchTaskType",
    "LocalRepositoryScanner",
    "DocumentFetcher",
    "LogFetcher",
    "ErrorFetcher",
    "ResearchFetchError",
    "ResearchFetchResult",
    "ResearchEvidenceNormalizationError",
    "ResearchEvidenceNormalizationResult",
    "ResearchEvidenceNormalizer",
    "MalformedResearchEvidenceError",
    "ResearchPacketAssemblyError",
    "MalformedResearchPacketInputError",
    "ResearchPacketAssembler",
    "assemble_research_packet",
    "ResearchPipelineError",
    "MalformedResearchPipelineInputError",
    "ResearchPipeline",
    "ResearchPipelineResult",
    "run_research_pipeline",
    "MalformedRepositoryScanRequestError",
    "RepositoryScanError",
    "RepositoryScanResult",
    "MalformedResearchFetchRequestError",
    "SourceHandle",
    "SourcePolicy",
    "SourceType",
    "MalformedResearchRequestError",
    "MalformedSourcePolicyError",
    "scan_local_repository",
    "normalize_research_request",
    "normalize_research_evidence",
]
