"""Memory foundation for the runtime."""

from qwen3_coder_next.memory.contracts import MemoryEntry, MemoryKind
from qwen3_coder_next.memory.exceptions import DuplicateMemoryError, MemoryNotFoundError
from qwen3_coder_next.memory.manager import MemoryManager
from qwen3_coder_next.memory.schemas import (
    MEMORY_SCHEMA_VERSION,
    GlobalPattern,
    MemoryEvent,
    MemoryItem,
    MemoryQuery,
    MemoryResult,
    MemoryTier,
    ProjectDecision,
    RetentionPolicy,
    SessionSummary,
)
from qwen3_coder_next.memory.serialization import (
    MalformedMemorySerializedDataError,
    MemorySerializationError,
    MemorySerializer,
    deserialize_global_pattern,
    deserialize_memory_event,
    deserialize_memory_item,
    deserialize_memory_query,
    deserialize_memory_result,
    deserialize_memory_revision,
    deserialize_memory_state,
    deserialize_project_decision,
    deserialize_retention_policy,
    deserialize_session_summary,
    serialize_global_pattern,
    serialize_memory_event,
    serialize_memory_item,
    serialize_memory_query,
    serialize_memory_result,
    serialize_memory_revision,
    serialize_memory_state,
    serialize_project_decision,
    serialize_retention_policy,
    serialize_session_summary,
)
from qwen3_coder_next.memory.project_store import (
    PROJECT_MEMORY_STORE_SCHEMA_VERSION,
    ProjectMemoryStore,
)
from qwen3_coder_next.memory.retrieval import MemoryRetriever, retrieve_memory
from qwen3_coder_next.memory.session_store import (
    SESSION_MEMORY_STORE_SCHEMA_VERSION,
    SessionMemoryStore,
)
from qwen3_coder_next.memory.state import MemoryRevision, MemoryState
from qwen3_coder_next.memory.store import MemoryStore

__all__ = [
    "DuplicateMemoryError",
    "MemoryEntry",
    "MemoryKind",
    "MEMORY_SCHEMA_VERSION",
    "MemoryEvent",
    "MemoryItem",
    "MemoryManager",
    "MemoryQuery",
    "MemoryResult",
    "MemoryRevision",
    "MemorySerializationError",
    "MalformedMemorySerializedDataError",
    "MemorySerializer",
    "MemoryState",
    "MemoryStore",
    "MemoryTier",
    "GlobalPattern",
    "PROJECT_MEMORY_STORE_SCHEMA_VERSION",
    "ProjectDecision",
    "ProjectMemoryStore",
    "MemoryRetriever",
    "SESSION_MEMORY_STORE_SCHEMA_VERSION",
    "SessionMemoryStore",
    "RetentionPolicy",
    "retrieve_memory",
    "SessionSummary",
    "MemoryNotFoundError",
    "deserialize_global_pattern",
    "deserialize_memory_event",
    "deserialize_memory_item",
    "deserialize_memory_query",
    "deserialize_memory_result",
    "deserialize_memory_revision",
    "deserialize_memory_state",
    "deserialize_project_decision",
    "deserialize_retention_policy",
    "deserialize_session_summary",
    "serialize_global_pattern",
    "serialize_memory_event",
    "serialize_memory_item",
    "serialize_memory_query",
    "serialize_memory_result",
    "serialize_memory_revision",
    "serialize_memory_state",
    "serialize_project_decision",
    "serialize_retention_policy",
    "serialize_session_summary",
]
